branch-defaults:
  master:
    environment: null
    group_suffix: null
global:
  application_name: mgl_backend
  branch: null
  default_ec2_keyname: mgl_backend_eb
  default_platform: Node.js 14 running on 64bit Amazon Linux 2
  default_region: ap-southeast-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
